name: Build & Deploy

on:
  push:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    if: "contains(github.event.head_commit.message, 'deploy')"

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build site
        env:
          TORCHLIGHT_API_TOKEN: ${{ secrets.TORCHLIGHT_API_TOKEN }}
        run: |
          npm install
          npm run prod

      - name: Commit /build_production
        run: |
          git config --global user.email "julien@julienbourdeau.com"
          git config --global user.name "Github Actions"
          git add -f build_production
          git commit -m 'Build static site'

      - name: Push to static branch
        run: git push origin $(git subtree split --prefix build_production v8):static --force
